site_name: Win10Guide
site_url: https://phense.github.com/win10guide/
site_description: 'Installation and Setup Guide for Windows 10'
site_author: 'Peter Hense'

markdown_extensions:
    - admonition
    - extra
    - sane_lists
    - smarty

plugins:
    - search
    - bootstrap-tables

extra_css:
    - css/extra.css

theme:
    name: mkdocs #readthedocs
    nav_style: dark
    shortcuts:       # https://keycode.info
        next: 39     # ->
        previous: 37 # <-
        search: 83  # s

nav:
    - Home: 'index.md'
    - Installation:
        - 'Drives, Partitions and Programs': 'drives.md'
        - 'Backup': 'backup-1.md'
        - 'Install': 'install.md'
    - Setup:
        - 'Post-Install': 'postinstall.md'
        - 'Security': 'security.md'
        - 'Basic Tools': 'basics.md'
        - 'Browser': 'browser.md'
        - 'The Editor': 'editor.md'
        - 'Audio': 'audio.md'
    - Supplementary:
        - 'Partitions': 'partitions.md'
        - 'References': 'references.md'
    - About: 'about.md'
