site_name: Win10Guide
site_url: https://phense.github.com/win10guide/
site_description: 'Installation and Setup Guide for Windows 10'
site_author: 'Peter Hense'

markdown_extensions:
    - admonition
    - attr_list
    - extra
    - sane_lists
    - smarty

plugins:
    - search

extra:
  generator: false

extra_css:
    - css/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

theme:
    name: material
    features:
      - navigation.instant
      - navigation.tracking
      - navigation.tabs
#      - navigation.tabs.sticky
      - navigation.top
      - toc.integrate
    palette:
      scheme: default
      primary: blue

nav:
    - Home: 'index.md'
    - Installation:
        - 'Drives, Partitions and Programs': 'drives/index.md'
        - 'Pre-Installation Backup': 'pre-install-backup/index.md'
        - 'Install': 'install.md'
    - Setup:
        - 'Post-Install': 'postinstall.md'
        - 'Security': 'security.md'
        - 'Basic Tools': 'basics.md'
        - 'Browser': 'browser.md'
        - 'The Editor': 'editor.md'
        - 'Audio': 'audio.md'
    - Supplementary:
        - 'Making Space': 'making-space/index.md'
        - 'Splitting a Partition': 'splitting-a-partition/index.md'
        - 'References': 'references.md'
    - About: 'about.md'
